### PR TITLE
Add newer PHP versions to Travis config

### LINKED ISSUE #15: Test with latest php version
This script tested till php 7.0. Now required testing with 8.0 and update `.travis` with latest version of php

### PR DESCRIPTION
**Pull request by red-led**
fixes #15

### CODE REVIEW

**Comment by thamaraiselvam** [comment]
@red-led Thanks for PR. 
PHP 8.0 version is failed. Can you fix it? https://app.travis-ci.com/github/thamaraiselvam/mysql-import/jobs/543155369

**Comment by thamaraiselvam** [comment]
@red-led I think it did not do trick.

**Comment by red-led** [comment]
Yep. I's complicated. There's no single compatible PHPUnit versions that support both 7.1 and 8.0.
If you're ok with new dependency may be polyfills will work...

**Comment by thamaraiselvam** [comment]
Appreciate your work 💯

**Pull request merged**
